name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: check out repository
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/checkout@v3
        with: 
          node-version: 'lts/*'
      - name: Install bats
        run: npm install 
     
         